## Kubernetes Cluster

You can deploy a Kubernetes cluster on a local machine, cloud, on-prem datacenter, or choose a managed Kubernetes cluster.
This lab uses managed cluster provided by Azure using the Azure Kubernetes Service (AKS).

_Azure Kubernetes Service (AKS)_ is a managed Kubernetes service that lets you quickly deploy and manage clusters.

_Minikube_ is a tool that makes it easy to run Kubernetes locally. 
Minikube runs a single-node Kubernetes cluster inside a Virtual Machine (VM) on your laptop for users looking to try out Kubernetes or develop with it day-to-day. Follow link:https://kubernetes.io/docs/tasks/tools/install-minikube/[Install Minikube] to install on your laptop.

Some of widely adopted distributions are:

- Red Hat OpenShift
- Rancher

Other managed Kubernetes cluster provided by other cloud providers are:

- Amazon EKS
- Azure Red Hat OpenShift Managed Service
- Google Kubernetes Engine (GKE)

### Creating AKS Cluster

Install Azure CLI locally, and login using Azure credentials. If you need to install or upgrade, see link:https://docs.microsoft.com/en-us/cli/azure/install-azure-cli[Install Azure CLI]. Verify the version installed is 2.0.64 or later.
[source,bash]
----
$ az --version
----

The following steps creates a cluster named `myAKSCluster` with two nodes:

. Create resource group. An Azure resource group is a logical group in which Azure resources are deployed and managed.
+
[source,bash]
----
$ az group create --name myResourceGroup --location eastus
----
. Create AKS cluster. This will take several minutes to complete.
+
[source,bash]
----
$ az aks create --resource-group myResourceGroup \
    --name myAKSCluster \
    --node-count 2 \
    --enable-addons monitoring --generate-ssh-keys
----
. Connect to the cluster. Install `kubectl` locally, use the `az aks install-cli` command:
+
[source,bash]
----
$ az aks install-cli
----
. Downloads credentials and configures the Kubernetes CLI.
+
[source,bash]
----
$ az aks get-credentials --resource-group myResourceGroup --name myAKSCluster
----

### Accessing the Cluster

To verify the connection to your cluster, use the `kubectl` command to list cluster nodes.
[source,bash]
----
$ kubectl get nodes
NAME                                STATUS   ROLES   AGE   VERSION
aks-nodepool1-26004593-vmss000000   Ready    agent   34m   v1.17.11
aks-nodepool1-26004593-vmss000001   Ready    agent   34m   v1.17.11
----
