## Creating your Cluster

You can deploy a Kubernetes cluster on a local machine, cloud, on-prem datacenter, or choose a managed Kubernetes cluster.
This lab uses link:https://labs.play-with-k8s.com/[Play with Kubernetes], which allows users to run K8s clusters in a matter of seconds.

Azure Kubernetes Service (AKS) is a managed Kubernetes service that lets you quickly deploy and manage clusters.
Use link:https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough-portal#create-an-aks-cluster[Create an AKS cluster] to create a AKS cluster.

_Minikube_ is a tool that makes it easy to run Kubernetes locally. 
Minikube runs a single-node Kubernetes cluster inside a Virtual Machine (VM) on your laptop for users looking to try out Kubernetes or develop with it day-to-day. Follow link:https://kubernetes.io/docs/tasks/tools/install-minikube/[Install Minikube] to install on your laptop.

Some of widely adopted distributions are:
* _Red Hat OpenShift_
* _Rancher_

Other managed Kubernetes cluster provided by other cloud providers are:
* _Amazon EKS_
* _Azure Red Hat OpenShift Managed Service_
* _Google Kubernetes Engine (GKE)_  

### Accessing the Cluster

To verify the connection to your cluster, use the `kubectl` command to list cluster information.
From the terminal within Play with Kubernetes, use the following command:
[source,bash]
----
$ kubectl cluster-info
Kubernetes master is running at https://192.168.0.13:6443
KubeDNS is running at https://192.168.0.13:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
----
